name: Docker

on:
  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - develop

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: brewblox-froghop-kettles

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup Pip
        uses: BSFishy/pip-action@v1
        with:
          packages: poetry

      - name: Install dependencies
        run: poetry install

      - name: Build Service
        run: bash ./docker/before_build.sh

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker/docker-compose.test.yml build
            docker-compose --file docker/docker-compose.test.yml run sut
          else
            docker build . --file docker/Dockerfile
          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup Pip
        uses: BSFishy/pip-action@v1
        with:
          packages: poetry

      - name: Install dependencies
        run: poetry install

      - name: Build Service
        run: bash ./docker/before_build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: trottmpq/brewblox-froghop-kettles:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
